# 在使用前请先阅读 README.md
# Please read README.md before use this theme

# favicon.ico 和 icon.png 都存放在 source 文件夹中
# "favicon.ico" and "icon.png" are stored in "source" folder
favicon: favicon.ico
icon: icon.png

# 选择是否启用黑色模式
# choose whether to use dark mode or not
dark: false

# 作者简介，内容会显示在 about 页面上
# author descriptions, all these information will be displayed on about page
author:
  name: "Pcrab"
  self_intro: "一个普通的大学生，爱好计算机，懒"
  social:
    github: "pcrab"
    email: "pcrab@mailbox.org"
    telegram: "Pcrab"
    instagram: ""
    twitter: ""
    weibo: ""
    zhihu: ""
    youtube: ""

# 目前仅提供cc协议
# currently only proviede cc
copyright:
  # 显示版权信息，0为关闭，1为对所有post生效，2为对文章中有"copyright: true"的文章才生效
  # Show copyright info, 0 for close, 1 for all posts, 2 for all posts with "copyright: true"
  open: 1
  # 是否可被商用，0为不可，1为可
  # whether can be used commercially, 0 for no, 1 for ok
  commercial: 0
  # 是否可被演绎，0为不可，1为在相同方式下可，2为可
  # whether can be changed, 0 for no, 2 for ok, 1 for ok in the same circumstance
  derivative: 1

# 使用的是 highlight.js 的 xcode 主题，我只选配了我个人使用的一些语言，建议根据自己的需要在 https://highlightjs.org/download/ 中选择自己需要的并替换 js 文件
# Using highlight.js xcode theme, and I only select some of my using languages. It is highly recommended to select your own languages on https://highlightjs.org/download/ and replace the default js file.
syntax:
  enable: true
  theme: xcode
  linenumber: true

comment:
  # 在此选择要使用的评论系统
  # Please select Disqus or Valine
  Select: Waline
  # 请访问 https://valine.js.org/ 并按照教程来配置使用 Valine 评论系统
  # Please visit https://valine.js.org/ to lean how to get appid and appkey
  Valine:
    appid: 9AaAihTp8toKHdarNTGPECXE-MdYXbMMI
    appkey: HUqCC6V8Difk8QVuDP5t00hs
  Waline:
    serverURL: ""
    visitor: true
  # 推荐使用 Disqus
  # Recommended
  Disqus:
    shortname: pcrab-blog
    # 如果需要代理，请访问 https://github.com/fooleap/disqus-php-api 来参考配置
    # 注意，要使用代理，你首先需要一台能够访问 Disqus 的服务器
    # If you need proxy, please visit https://github.com/fooleap/disqus-php-api to learn how to do so
    # Important: you need a VPS which can connect to Disqus
    needProxy: false
    # 此处填写你的反代服务器的域名。请自行搭建，我的是不能直接让你用的。
    # here is your proxy server's domain. Please use your own server, don't directly use mine, as its impossible for you to use
    proxyUrl: https://disqus.pcrab.xyz
  LiveRe:
    datauid: MTAyMC81MTAyMi8yNzUwNA==
  Gitalk:
    clientID: 
    clientSecret: 
    owner:
    repo:
  # 需要自建,或付费使用官方版本（有试用）
  # Need self host, or pay to use official version
  Commento:
    # 输入自建时使用的域名，如果使用的是官方版本，应为https://cdn.commento.io，最后不要加斜杠
    # Please use your domain if you are self hosted. If you use the cloud service, the domain is https://cdn.commento.io, with no / at the end
    domain: https://commento.pcrab.xyz



# 友链
# friendlink
friendlink:
  enable: true
  links:
    - { name: "LJY's Blog", url: "https://blog.ljyngup.com", cover: "https://ljyngupdownload.oss-cn-hangzhou.aliyuncs.com/2018/07/LJYblog-300x300.jpg"}
    - { name: "Sukoshi", url: "https://sukoshi.xyz/", desc: "十八岁基层程序猿想做涩影狮", cover: "https://s.gravatar.com/avatar/2d6b803eea37de0257620d5fabee7e64?s=200&r=g&d=retro" }

# 网站成立时间，若大于等于当前年份则不会显示
# The start year of the site which won't be shown if is beyond current
startYear: 2020

# 显示页脚主题信息
# show theme info
showTheme: true

# 不蒜子网页统计
# busuanzi
busuanzi:
  enable: true

# 备案
beian:

rss: true
